version: '3.8'
services:
  aprs:
    image: ghcr.io/sdr-enthusiasts/docker-aprs-tracker
    container_name: aprs
    hostname: aprs
    restart: always
    device_cgroup_rules:
      - 'c 189:* rwm'
    environment:
      - VERBOSE=true
    tmpfs:
      - /tmp
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
      - /dev:/dev:ro
