version: '3.8'
services:
  aprs:
    #image: ghcr.io/sdr-enthusiasts/docker-aprs-tracker
    build: https://github.com/sdr-enthusiasts/docker-aprs-tracker.git
    container_name: aprs
    hostname: aprs
    restart: always
    device_cgroup_rules:
      - 'c 189:* rwm'
    privileged: true
    environment:
      - VERBOSE=false
      - MYCALL=KX1T-1
    tmpfs:
      - /run:exec,size=32M
      - /tmp:size=32M
      - /var/log:size=32M
    ports:
       - 2947:2947
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
      - /dev:/dev:ro