version: '3.8'
services:
  vesselalert:
    image: ghcr.io/sdr-enthusiasts/vesselalert
    container_name: vesselalert
    hostname: vesselalert
    restart: always
    environment:
      # mandatory parameters:
      - AIS_URL=http://my.ais-catcher/website:8100
      - MASTODON_SERVER=airwaves.social
      - MASTODON_ACCESS_TOKEN=my_mastodon_token
      # optional parameters that you may want to set:
      - MASTODON_SKIP_FILTER=
      - MASTODON_MIN_DIST=
      - MASTODON_NOTIFY_EVERY=86400
      - MASTODON_CUSTOM_FIELD=
      - MASTODON_POST_VISIBILITY=unlisted
      - MASTODON_LINK_SHIPXPLORER=on
      - MASTODON_LINK_MARINETRAFFIC=on
      - MASTODON_LINK_VESSELFINDER=on
      - NOTIFICATION_MAPURL=yes
      - NOTIFICATION_THROTTLE=on
      - NOTIFY_ONLY_NEW_ON_STARTUP=on
      - SCREENSHOT_URL=http://ais-screenshot:5042
      # optional parameters that you probably don't want to touch unless you really know what you are doing:
      - CHECK_INTERVAL=30
      - VESSELDBFILE=/data/vessel.db
      - VESSELDBLOCK=/run/vesseldb.lock
      - MIN_MSG_COUNT=10
      - MAX_MSG_AGE=86400
      - DEBUG=
    tmpfs:
      - /tmp
    volumes:
      - /opt/ais/data:/data
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"

# Optional Screenshot container
# We recommend using this only if your system has sufficient resources
# Note that is this container is ~250-300 Mb in download size
# and requires a lot of system resources when an image is retrieved
#
# To configure:
# - replace BASE_URL with the URL of your AIS-Catcher website.
# - you can add additional HTTP GET parameters to the MAP_ARGS variable
#   For example: - MAP_ARGS=zoom=11&map=mapnik
#
  ais-screenshot:
    image: ghcr.io/sdr-enthusiasts/screenshot:aiscatcher
    tty: true
    container_name: ais-screenshot
    hostname: ais-screenshot
    restart: always
    shm_size: 1gb
    environment:
      - LOAD_SLEEP_TIME=10
      - BASE_URL=http://my.ais-catcher/website:8100
      - MAXTIME=60
    ports:
      - 5042:5042
