#!/command/with-contenv bash
# shellcheck shell=bash external-sources=false disable=SC1091

source /scripts/common

s6wrap --quiet --timestamps --prepend="$(basename "$0")" --args echo "Starting DireWolf version $(cat /.CONTAINER_VERSION)"

