#!/command/with-contenv bash
# shellcheck shell=bash external-sources=false disable=SC1091

source /scripts/common

s6wrap --quiet --timestamps --prepend="$(basename "$0")" --args echo "Starting DireWolf version $(cat /.CONTAINER_VERSION)"
s6wrap --quiet --timestamps --prepend="$(basename "$0")" --args cat << EOM

docker-aprs-tracker - APRS tracker for vehicles using Direwolf, gpsd, and chrony
---------------------------------------------------------------------------------------------
Copyright (C) 2023, Ramon F. Kolb (kx1t)

This program is free software: you can redistribute it and/or modify it
under the terms of the GNU General Public License as published by the
Free Software Foundation, either version 3 of the License, or (at your option)
any later version.

This program is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with this program.
If not, see <https://www.gnu.org/licenses/>.
---------------------------------------------------------------------------------------------
Among other pieces of software, this container contains:
- Direwolf, Copyright: 2013-2023, John Langner, WB2OSZ; license: GPL-2
- gpsd, Copyright: 1997-2002, Remco Treffkorn; 2005, Eric S. Raymond; 1997-2018, GPSD project; license: BSD-3-clause
- chrony, Copyright: 2009-2021, Miroslav Lichvar; 1997-2007, Richard P. Curnow; license: GPL-2
---------------------------------------------------------------------------------------------
EOM

