#!/command/with-contenv bash
# shellcheck shell=bash

# Chronyd runtime. Sets the time of the system
#---------------------------------------------------------------------------------------------
# Copyright (C) 2023, Ramon F. Kolb (kx1t)
#
# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation, either version 2 of the License, or (at your option)
# any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with this program.
# If not, see <https://www.gnu.org/licenses/>.
#---------------------------------------------------------------------------------------------

#!/command/with-contenv bash
# shellcheck shell=bash disable=SC1091,SC2015,SC2164,SC2068,SC2145

source /scripts/common
s6wrap=(s6wrap --quiet --timestamps --prepend="$(basename "$0")" --args)

# make sure the chrony run directory exists and has the correct permissions:
mkdir -p /run/chrony
chmod 0750 /run/chrony

CHRONY_BIN="/usr/sbin/chronyd"

CHRONY_ARGS=("-d")
CHRONY_ARGS+=("-F 1")

# Wait until GPSD is running:
while ! pgrep gpsd >/dev/null 2>&1; do
    sleep 1
done

# Wait until GPSD is established
sleep 10

"${s6wrap[@]}" echo "[INFO] Starting: $CHRONY_BIN ${CHRONY_ARGS[@]}"
#shellcheck disable=SC2048,SC2086
"${s6wrap[@]}" $CHRONY_BIN ${CHRONY_ARGS[*]}

"${s6wrap[@]}" echo "[WARNING] Exited, restarting in 10 secs"
sleep 10