#!/command/with-contenv bash
# shellcheck shell=bash

# GPSD runtime.
#---------------------------------------------------------------------------------------------
# Copyright (C) 2023, Ramon F. Kolb (kx1t)
#
# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation, either version 2 of the License, or (at your option)
# any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with this program.
# If not, see <https://www.gnu.org/licenses/>.
#---------------------------------------------------------------------------------------------

#!/command/with-contenv bash
# shellcheck shell=bash disable=SC1091,SC2015,SC2164,SC2068,SC2145

source /scripts/common
s6wrap=(s6wrap --quiet --timestamps --prepend="$(basename "$0")" --args)

GPSD_BIN="/sbin/gpsd"

GPSD_ARGS=(--nowait)
if chk_disabled "$GPSD_START_DAEMON"; then GPSD_ARGS+=(--foreground); fi
if chk_enabled "$VERBOSE"; then VERBOSE="1"; fi
if [[ -n "$VERBOSE" ]]; then GPSD_ARGS+=(--debug "$VERBOSE"); fi
if [[ -n "$GPSD_SOCKET" ]]; then GPSD_ARGS+=(--sockfile "$GPSD_SOCKET"); fi
if [[ -n "$GPSD_OPTIONS" ]]; then GPSD_ARGS+=("$GPSD_OPTIONS"); fi
GPSD_ARGS+=("${GPSD_DEVICES}")

"${s6wrap[@]}" echo "[INFO] Starting: $GPSD_BIN ${GPSD_ARGS[@]}"
#shellcheck disable=SC2048,SC2086
"${s6wrap[@]}" $GPSD_BIN ${GPSD_ARGS[*]} \
    | grep -vi "Cannot assign requested address" \
    | grep -vi "unable to connect to the DBUS system bus" \
    || true

"${s6wrap[@]}" echo "[WARNING] Exited, restarting in 10 secs"
sleep 10